import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/_components/Header";
import { CustomMetadata, RootLayoutProps } from "@/interfaces/layout";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


const inter = Inter({ subsets: ["latin"] });

export const metadata: CustomMetadata = {
  title: "Realtor-clone",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div>{children}</div>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
      </body>
    </html>
  );
};

export default RootLayout;
